MONGO_DB:
  URL: mongodb+srv://villagersAtlas:<password>@villagersatlas.tnakuyj.mongodb.net/?retryWrites=true&w=majority&appName=villagersAtlas
  PORT: 27017
  USERNAME: villagersDbUser
  PASSWORD: warewolf
  DB: villagers
  COL: games