version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - C:/mongodb/db:/data/db
      
  flask_app:
    image: villagersflaskapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    container_name: villagersRunningFlaskApp
    ports:
      - 5000:5000
    environment:
      IN_DOCKER: "YES"
      MONGO_URI: "mongodb://root:rootpassword@mongodb_container:27017/"
    depends_on:
      - mongodb_container
