# mongo-container:
#   image: mongo
#   environment:
#       # provide your credentials here
#       - MONGO_INITDB_ROOT_USERNAME=admin
#       - MONGO_INITDB_ROOT_PASSWORD=password
#   ports:
#     - "27017:27017"
#   # no --auth is needed here as presence of username and password add this option automatically
#   command: mongod

version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - C:/mongodb/db:/data/db 

# volumes:
#   mongodb_data_container: